### ISSUE TITLE
[Roadmap issue] Short-term hardening

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p-pubsub#220]
Features needed by Filecoin and ETH2, in order of priority:

- [X] Expose the peer that propagated the message to us (#218)
- [X] Subscription options, which enables...
- [x] Topic handles (#198), so we can...
- [ ] Configurable per-topic max message sizes (#209).
- ~[ ] Duplicate consumption (#216), which is blocked by...~
- ~[ ] Validator cache (we don’t want to validate dupes over and over again, requires message signing to be enabled).~
- [x] Configurable outbound peer queue sizes (#217).
- [ ] Make Publish() report problems / coalesce queued messages (#217).
- [ ] Mark topics as relay-only (#28).
- [ ] Relative prioritization of traffic per topic (needs to be designed and thought carefully) (#210).

**Comment by vyzo** [comment]
Duplicate consumption can be implemented by the application through a custom tracer, just like the score subsystem plugs into the tracer.
The validator cache, which is complex, is then unecessary.
